"""
Streamlit SOC dashboard. Talks to the FastAPI backend over HTTP.
Run the API first (uvicorn src.api:app), then: streamlit run dashboard/app.py
"""
import os
import requests
import streamlit as st

API_BASE = os.getenv("API_BASE_URL", "http://localhost:8000")

st.set_page_config(page_title="AI-Powered Cloud SOC", layout="wide")
st.title("🛡️ AI-Powered Cloud SOC & Threat Detection Dashboard")

# ---- Fetch data ----
try:
    metrics = requests.get(f"{API_BASE}/metrics", timeout=5).json()
    alerts = requests.get(f"{API_BASE}/alerts", timeout=5).json()
except requests.exceptions.ConnectionError:
    st.error("⚠️ Can't reach the API. Start it first: `uvicorn src.api:app --reload`")
    st.stop()

# ---- Top metrics row ----
col1, col2, col3, col4, col5 = st.columns(5)
col1.metric("Total Incidents", len(alerts))
col2.metric("Detection Rate (Recall)", f"{metrics.get('recall', 0) * 100:.1f}%")
col3.metric("Precision", f"{metrics.get('precision', 0) * 100:.1f}%")
col4.metric("False Positive Rate", f"{metrics.get('false_positive_rate', 0) * 100:.1f}%")
col5.metric("F1 Score", f"{metrics.get('f1_score', 0):.3f}")

st.divider()

# ---- Severity filter ----
severities = sorted(set(a["severity"] for a in alerts),
                     key=lambda s: ["Critical", "High", "Medium", "Low"].index(s))
selected = st.multiselect("Filter by severity", severities, default=severities)
filtered = [a for a in alerts if a["severity"] in selected]

st.subheader(f"🚨 Alerts ({len(filtered)})")

SEVERITY_COLOR = {"Critical": "🔴", "High": "🟠", "Medium": "🟡", "Low": "🟢"}

for alert in filtered:
    header = (f"{SEVERITY_COLOR.get(alert['severity'], '⚪')} **{alert['incident_id']}** "
              f"— risk {alert['risk_score']}/100 ({alert['severity']}) — user: {alert['user']}")
    with st.expander(header):
        c1, c2 = st.columns([1, 1])

        with c1:
            st.markdown("**MITRE ATT&CK Techniques**")
            for t in alert["mitre_techniques"]:
                st.markdown(f"- `{t['technique_id']}` {t['technique_name']} ({t['tactic']})")

            st.markdown("**Behavioral Features**")
            st.json(alert["features"])

        with c2:
            if st.button("🔍 Run LLM Investigation", key=f"inv_{alert['incident_id']}"):
                with st.spinner("Generating investigation..."):
                    inv = requests.get(
                        f"{API_BASE}/alerts/{alert['incident_id']}/investigate", timeout=30
                    ).json()

                if "llm_output" in inv:
                    st.markdown("**LLM-Generated Investigation**")
                    st.markdown(inv["llm_output"])
                else:
                    st.markdown("**Timeline**")
                    st.code(inv.get("timeline", ""), language=None)
                    st.markdown("**Evidence Summary**")
                    st.write(inv.get("summary", ""))
                    st.markdown("**Recommended Next Steps**")
                    for step in inv.get("recommended_steps", []):
                        st.markdown(f"- {step}")
                    if "note" in inv:
                        st.caption(inv["note"])
                    st.caption(f"Generated by: {inv.get('generated_by', 'unknown')}")

st.divider()
st.caption(
    "Detection: Isolation Forest (unsupervised) on behavioral features | "
    "Risk scoring: weighted anomaly + MITRE severity + frequency | "
    "Investigation: LLM-assisted, grounded in retrieved incident logs"
)
